=== JesusAlvaarez/JesusAlvaarez.github.io/recursosWeb/subSitiosEntretenimiento/respuestasForms/datosXML/lasMejoresPeliculas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:element name="Lista">
      <xs:complexType>
         <xs:sequence>
            <xs:element name="Pelicula" maxOccurs="unbounded">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name="NombreDeLaPelicula" type="xs:string" />
                     <xs:element name="FechaDeEstreno" type="xs:string" />
                     <xs:element name="Calificacion" type="xs:string" />
                  </xs:sequence>
               </xs:complexType>
            </xs:element>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
</xs:schema>

=== JesusAlvaarez/JesusAlvaarez.github.io/recursosWeb/subSitiosEntretenimiento/respuestasForms/datosXML/lasMejoresPeliculas.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Lista xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="lasMejoresPeliculas.xsd">
        <Pelicula>
           <NombreDeLaPelicula>El padrino</NombreDeLaPelicula>
           <FechaDeEstreno>1972</FechaDeEstreno>
           <Calificacion>9.6</Calificacion>
        </Pelicula>
        <Pelicula>
            <NombreDeLaPelicula>El se√±or de los anillos</NombreDeLaPelicula>
            <FechaDeEstreno>2003</FechaDeEstreno>
            <Calificacion>9.2</Calificacion>
         </Pelicula>
         <Pelicula>
            <NombreDeLaPelicula>La vida es bella</NombreDeLaPelicula>
            <FechaDeEstreno>1998</FechaDeEstreno>
            <Calificacion>8.9</Calificacion>
         </Pelicula>
         <Pelicula>
            <NombreDeLaPelicula>The Avengers</NombreDeLaPelicula>
            <FechaDeEstreno>2012</FechaDeEstreno>
            <Calificacion>9.1</Calificacion>
         </Pelicula>
         <Pelicula>
            <NombreDeLaPelicula>La lista de Schindler</NombreDeLaPelicula>
            <FechaDeEstreno>1993</FechaDeEstreno>
            <Calificacion>9.5</Calificacion>
         </Pelicula>
         <Pelicula>
            <NombreDeLaPelicula>Forrest Gump</NombreDeLaPelicula>
            <FechaDeEstreno>1993</FechaDeEstreno>
            <Calificacion>9.3</Calificacion>
         </Pelicula>
         <Pelicula>
            <NombreDeLaPelicula>Batman:El caballero de la noche</NombreDeLaPelicula>
            <FechaDeEstreno>2008</FechaDeEstreno>
            <Calificacion>9.2</Calificacion>
         </Pelicula>
         <Pelicula>
            <NombreDeLaPelicula>Soy leyenda</NombreDeLaPelicula>
            <FechaDeEstreno>2007</FechaDeEstreno>
            <Calificacion>7.5</Calificacion>
         </Pelicula>
         <Pelicula>
            <NombreDeLaPelicula>El padrino: Parte II</NombreDeLaPelicula>
            <FechaDeEstreno>1974</FechaDeEstreno>
            <Calificacion>9.6</Calificacion>
         </Pelicula>
         <Pelicula>
            <NombreDeLaPelicula>Tiempos Violentos</NombreDeLaPelicula>
            <FechaDeEstreno>1994</FechaDeEstreno>
            <Calificacion>8.9</Calificacion>
         </Pelicula>
</Lista>

=== JesusAlvaarez/JesusAlvaarez.github.io/datosXML/lasMejoresPeliculas.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Lista xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="lasMejoresPeliculas.xsd">
        <Pelicula>
           <NombreDeLaPelicula>El padrino</NombreDeLaPelicula>
           <FechaDeEstreno>1972</FechaDeEstreno>
           <Calificacion>9.6</Calificacion>
        </Pelicula>
        <Pelicula>
            <NombreDeLaPelicula>El se√±or de los anillos</NombreDeLaPelicula>
            <FechaDeEstreno>2003</FechaDeEstreno>
            <Calificacion>9.2</Calificacion>
         </Pelicula>
         <Pelicula>
            <NombreDeLaPelicula>La vida es bella</NombreDeLaPelicula>
            <FechaDeEstreno>1998</FechaDeEstreno>
            <Calificacion>8.9</Calificacion>
         </Pelicula>
         <Pelicula>
            <NombreDeLaPelicula>The Avengers</NombreDeLaPelicula>
            <FechaDeEstreno>2012</FechaDeEstreno>
            <Calificacion>9.1</Calificacion>
         </Pelicula>
         <Pelicula>
            <NombreDeLaPelicula>La lista de Schindler</NombreDeLaPelicula>
            <FechaDeEstreno>1993</FechaDeEstreno>
            <Calificacion>9.5</Calificacion>
         </Pelicula>
         <Pelicula>
            <NombreDeLaPelicula>La lista de Schindler</NombreDeLaPelicula>
            <FechaDeEstreno>1993</FechaDeEstreno>
            <Calificacion>9.5</Calificacion>
         </Pelicula>
         <Pelicula>
            <NombreDeLaPelicula>La lista de Schindler</NombreDeLaPelicula>
            <FechaDeEstreno>1993</FechaDeEstreno>
            <Calificacion>9.5</Calificacion>
         </Pelicula>
         <Pelicula>
            <NombreDeLaPelicula>La lista de Schindler</NombreDeLaPelicula>
            <FechaDeEstreno>1993</FechaDeEstreno>
            <Calificacion>9.5</Calificacion>
         </Pelicula>
</Lista>
